rubocop:
  config_file: .rubocop.yml

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
